### ISSUE TITLE
Nozzle tutorial strict host key checking

### ISSUE THREAD

**Issue by roxtar** [cloudfoundry/docs-loggregator#3]
The underscores in `strict_host_key_checking` are italicized when turned to docs:

https://github.com/cloudfoundry/docs-loggregator/blob/master/nozzle-tutorial.html.md.erb#L256

https://docs.cloudfoundry.org/loggregator/nozzle-tutorial.html#view

**Comment by voelzmo** [comment]
You can probably just remove the `--strict_host_key_checking` option, it's no longer necessary to specify this for `bosh ssh`. cc: @cppforlife

**Comment by animatedmax** [comment]
Removed. Thank you, voelzmo
