### ISSUE TITLE
Invalid client in example

### ISSUE THREAD

**Issue by fhanik** [cloudfoundry/docs-loggregator#30]
Invalid client example:

https://github.com/cloudfoundry/docs-loggregator/blob/79b744c9c00880560ef14b8039d6901a0fc4da1a/nozzle-tutorial.html.md.erb#L47-L53

If this client requires a browser flow, then `redirect-uri` is a required property. Maybe this client requires `client_credentials` only, and it's just a copy paste error?

**Comment by cf-pub-tools** [comment]
Hi @fhanik This should be corrected with commit 03a68e52d2199ba6134c15e9507d88afc37c12e5
