### ISSUE TITLE
nozzle-tutorial using ssh to clone is unnecessary and difficult

### ISSUE THREAD

**Issue by matthewfischer** [cloudfoundry/docs-loggregator#34]
the nozzle tutorial uses ssh to clone repos and sub-modules. This requires that you have:

- a github account
- a key registered on the account
- your ssh keys on the box you are cloning to

This is unecessarily complex and breaks work flows where people are using a shared jumpbox. Since this is just an example, is a public repo, and not for development, can we switch these checkouts over to https?

```
ubuntu@bosh-stemcell:~/example-nozzle-release$ git submodule update --init --recursive
Cloning into 'src/github.com/cloudfoundry-incubator/example-nozzle'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:cloudfoundry-incubator/example-nozzle.git' into submodule path 'src/github.com/cloudfoundry-incubator/example-nozzle' failed
```

**Comment by matthewfischer** [comment]
Work-around:

git clone https://github.com/cloudfoundry-incubator/example-nozzle-release.git

Apply this diff

`ubuntu@bosh-stemcell:~/example-nozzle-release$ git diff
diff --git a/.gitmodules b/.gitmodules
index 73e1200..e0741d2 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,18 +1,18 @@
 [submodule "src/github.com/cloudfoundry-incubator/example-nozzle"]
        path = src/github.com/cloudfoundry-incubator/example-nozzle
-       url = git@github.com:cloudfoundry-incubator/example-nozzle.git
+       url = https://github.com/cloudfoundry-incubator/example-nozzle.git
 [submodule "src/github.com/cloudfoundry-incubator/uaago"]
        path = src/github.com/cloudfoundry-incubator/uaago
-       url = git@github.com:cloudfoundry-incubator/uaago.git
+       url = https://github.com/cloudfoundry-incubator/uaago.git
 [submodule "src/github.com/cloudfoundry/noaa"]
        path = src/github.com/cloudfoundry/noaa
-       url = git@github.com:cloudfoundry/noaa.git
+       url = https://github.com/cloudfoundry/noaa.git
 [submodule "src/github.com/cloudfoundry/sonde-go"]
        path = src/github.com/cloudfoundry/sonde-go
-       url = git@github.com:cloudfoundry/sonde-go.git
+       url = https://github.com/cloudfoundry/sonde-go.git
 [submodule "src/github.com/gogo/protobuf"]
        path = src/github.com/gogo/protobuf
-       url = git@github.com:gogo/protobuf.git
+       url = https://github.com/gogo/protobuf.git
 [submodule "src/github.com/gorilla/websocket"]
        path = src/github.com/gorilla/websocket
-       url = git@github.com:gorilla/websocket.git
+       url = https://github.com/gorilla/websocket.git
`

Then init the submodules.

**Comment by ljarzynski** [comment]
Thanks for bringing this up @matthewfischer. I went ahead and changed the document to use HTTPS instead of SSH: https://github.com/cloudfoundry/docs-loggregator/commit/7c013dac967ea2038f0af92aacd18dee1da81ce6. The change should be reflected on the site shortly.
