### ISSUE TITLE
Logs Metrics Agent architecture enables a pull workflow, not push

### ISSUE THREAD

**Issue by zmb3** [cloudfoundry/docs-loggregator#43]
In the docs we say that you can use the logs metrics agent architecture _to use push-based metrics collection_.

https://github.com/cloudfoundry/docs-loggregator/blob/e5ff43187d3e5e78747c81d0caee8f230304251a/agent-architecture.html.md.erb#L55

But this architecture actually enables a Prometheus-style pull model, not push.  Right?

**Comment by mlimonczenko** [comment]
Hello @zmb3,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
