### ISSUE TITLE
Ambiguity in Shared-Nothing Architecture decription

### ISSUE THREAD

**Issue by mvadu** [cloudfoundry/docs-loggregator#50]
[Current documentation](https://github.com/cloudfoundry/docs-loggregator/blob/d20fb60e55f2a9086fde8cb40f7f852a9cc3815c/architecture.html.md.erb#L68) states "For example, the shared-nothing architecture does not require the Forwarder Agent, Syslog Agent, or Metrics Agent.", and the diagram linked as well as description do show syslog agent as well as [Forwarder agent](https://github.com/cloudfoundry/docs-loggregator/blob/d20fb60e55f2a9086fde8cb40f7f852a9cc3815c/architecture.html.md.erb#L86). 

Reading the documentation and the images, Shared Nothing actually shows more hops compared to the statements made otherwise.

**Comment by mlimonczenko** [comment]
Hello @mvadu,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
