### ISSUE TITLE
Can i modified cloud foundry system metrics?

### ISSUE THREAD

**Issue by ihocho** [cloudfoundry/docs-loggregator#6]
I checked the metrics on the below site.
https://docs.cloudfoundry.org/loggregator/all_metrics.html

Some Metrics on the page i could not find and some metrics are added newly.
for example - garden-linux.DepotDirs, garden-linux.loopDevices etc.
In addition, I would like to get Metrics' description - some metrics' description are blank.

Can i have updated information of cloud foundry metrics?

**Comment by jncd** [comment]
Metrics have now been updated. 
Thank you @ihocho for logging this issue!
