### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by haraldfuchs** [cloudfoundry/docs-loggregator#76]
The [documentation of container metrics](https://docs.cloudfoundry.org/loggregator/container-metrics.html) states:

> `absolute_entitlement` The amount of CPU time that a Diego Cell has allocated to an app instance.

and

> `absolute_usage` The CPU time that an app instance has used.

This lacks the time unit of the numerical values - I guess it's nanoseconds.

**Comment by rroberts2222** [comment]
Hi @haraldfuchs,
That is correct. The `absolute_entitlement` and `absolute_usage` metrics both use nanoseconds.

**Comment by anita-flegg** [comment]
Added to the doc in branches master and 22.0.
These metrics don't appear to exist before then.
